sources:
  - KMMIC/Sources/Supports/Helpers/Shared/Shared.tmp.generated.swift
templates:
  - tools/sourcery/templates/Shared.stencil
output:
  KMMIC/Sources/Supports/Helpers/Shared/Shared.generated.swift
