sources:
  - KMMIC/Sources/Supports/Helpers/Shared/AutoSharedUseCase.tmp.generated.swift
templates:
  - tools/sourcery/templates/AutoSharedUseCase.stencil
output:
  KMMIC/Sources/Supports/Helpers/Shared/AutoSharedUseCase.generated.swift
