sources:
  - KMMIC/Sources
forceParse:
  - generated
templates:
  - tools/sourcery/templates/AutoMockable.stencil
output:
  KMMICTests/Sources/Mocks/Sourcery
args:
  autoMockableTestableImports:
    - KMMIC
    - Shared
  autoMockableImports:
    - FlowStacks
