name: Running tests

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]

permissions:
  actions: write
  checks: write
  contents: write
  issues: write
  pull-requests: write
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ios_test:
    name: Running tests in iOS
    runs-on: macOS-12
    defaults:
      run:
        working-directory: ./ios
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Setup Java JDK
      uses: actions/setup-java@v2.1.0
      with:
       distribution: 'adopt'
       java-version: '11'

    - uses: actions/cache@v2
      id: bunlderCache
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-gems-

    - name: Bundle install
      run: bundle install --path vendor/bundle

    - name: Cache Pods
      uses: actions/cache@v2
      id: cocoapodCache
      with:
        path: Pods
        key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-pods-

    - name: Setup Konfig Properties
      env:
       BUILD_KONFIG_PROPERTIES: ${{ secrets.BUILD_KONFIG_PROPERTIES }}
      run: |
       touch ../buildKonfig.properties
       echo $BUILD_KONFIG_PROPERTIES | base64 --decode > ../buildKonfig.properties

    - name: Generate KMM frameworks for Cocoapods
      run: |
        cd ..
        ./gradlew generateDummyFramework

    - name: Install Pods Dependencies
      run: bundle exec pod install

    - name: Build and Test
      run: bundle exec fastlane buildAndTest
      env:
        CI: true

    - name: Clean up previous code coverage report
      run: bundle exec fastlane cleanUpOutput

    - name: Review pull request by Danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: bundle exec danger

  shared_test:
      name: Running tests in Shared
      runs-on: ubuntu-latest
      defaults:
        run:
          working-directory: ./shared
      steps:
      - uses: actions/checkout@v2

      - name: Setup Java JDK
        uses: actions/setup-java@v2.1.0
        with:
         distribution: 'adopt'
         java-version: '11'

      - name: Setup Konfig Properties
        env:
         BUILD_KONFIG_PROPERTIES: ${{ secrets.BUILD_KONFIG_PROPERTIES }}
        run: |
         touch ../buildKonfig.properties
         echo $BUILD_KONFIG_PROPERTIES | base64 --decode > ../buildKonfig.properties

      - name: Running tests
        run: |
          cd ..
          ./gradlew clean Shared:test

      - name: Run Detekt
        run: |
          cd ..
          ./gradlew detekt

      - name: Review pull request by Danger
        uses: danger/kotlin@1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
